import Document, { Head, Html, Main, NextScript } from "next/document";

class MyDocument extends Document {
  render() {
    return (
      <Html lang="en">
        <Head>
          <link rel="icon" href="/favicon.ico" />
          <meta
            name="description"
            content="Improve your child's reading skills with personalized passages generated by AI. Our website offers a wide range of topics and levels to choose from, making reading fun and educational. Start your child's reading journey today!"
          />
          <meta
            property="og:site_name"
            content="Your Child's Personal AI Reading Companion - Better Reading"
          />
          <meta
            property="og:description"
            content="Improve your child's reading skills with personalized passages generated by AI. Our website offers a wide range of topics and levels to choose from, making reading fun and educational. Start your child's reading journey today!"
          />
          <meta
            property="og:title"
            content="Your Child's Personal AI Reading Companion - Better Reading"
          />
          <meta name="twitter:card" content="summary_large_image" />
          <meta
            name="twitter:title"
            content="Your Child's Personal AI Reading Companion - Better Reading"
          />
          <meta
            name="twitter:description"
            content="Improve your child's reading skills with personalized passages generated by AI. Our website offers a wide range of topics and levels to choose from, making reading fun and educational. Start your child's reading journey today!"
          />
          <meta
            property="og:image"
            content="https://reading.llego.dev/betterreading.png"
          />
          <meta
            name="twitter:image"
            content="https://reading.llego.dev/betterreading.png"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;